import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const phone = process.argv[2] === 'phone';
const b = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage(phone ? { viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true } : { viewport: { width: 1280, height: 720 } });
const errs = []; p.setDefaultTimeout(240000);
p.on('pageerror', e => errs.push('PAGEERROR ' + e.message));
p.on('console', m => { if (m.type() === 'error' && !m.text().includes('Failed to load')) errs.push('ERR ' + m.text()); });
await p.addInitScript({ path: 'test/harness.js' });
await p.goto('file:///home/user/emojiRP/project-gel/dist/project-gel.html');
await p.waitForFunction(() => { try { return G.state === 'home'; } catch (_) { return false; } }, null, { timeout: 120000, polling: 200 });
await p.evaluate(() => { __manual(); G.save.coins = 9000; UI.refreshHome(); });
const fr = n => p.evaluate(n => __frames(n, 1 / 60, true), n);
await p.click('.tab[data-tab="skins"]'); await fr(40); await p.waitForTimeout(500);
await p.screenshot({ path: `test/shots/${phone ? 'phone-' : ''}blob-colors.png` });
await p.click('#skinGrid .skin:nth-child(10)'); await p.click('#blobTabs button[data-bt="costumes"]'); await p.click('#skinGrid .skin:nth-child(7)'); await fr(40); await p.waitForTimeout(500);
await p.screenshot({ path: `test/shots/${phone ? 'phone-' : ''}blob-costumes.png` });
console.log(errs.join('\n') || 'no errors');
await b.close();
